[[tables]]
name = 'user'
depends = ['account']

[[tables.column]]
name = 'id'
valueType = 'fk'
value = 'account:user_id'

[[tables.column]]
name = 'name'
valueType = 'fakeit'
value = '{name}'

[[tables.column]]
name = 'icon'
valueType = 'fakeit'
value = '{url}'

[[tables.column]]
name = 'created_at'
valueType = 'value'
value = '{now}'

[[tables]]
name = 'account'

[[tables.column]]
name = 'user_id'
valueType = 'fakeit'
value = '{digitn:36}'

[[tables.column]]
name = 'firebase_id'
valueType = 'fakeit'
value = '{digitn:36}'

[[tables.column]]
name = 'created_at'
valueType = 'value'
value = '{now}'
