[db]
name = 'db'
user = 'user'
password = 'password'
addr = 'localhost:3306'
net = 'tcp'
parseTime = false
location = 'Asia/Tokyo'
allowNativePasswords = true

[tables]
[[tables.table]]
name = 'user'

[[tables.table.column]]
name = 'id'
valueType = 'fakeit'
value = '????????????????????????????????????' # 36文字

[[tables.table.column]]
name = 'name'
valueType = 'fakeit'
value = '{person.first} {person.last}'

[[tables.table.column]]
name = 'icon'
valueType = 'fakeit'
value = '{object.url}'

[[tables.table.column]]
name = 'created_at'
valueType = 'value'
value = 'datetime'
