[db]
name = 'db'
user = 'user'
password = 'password'
addr = 'localhost:3306'
net = 'tcp'
parseTime = false
location = 'Asia/Tokyo'
allowNativePasswords = true

[tables]
[[tables.table]]
name = 'account'

[[tables.table.column]]
name = 'user_id'
valueType = 'fakeit'
value = '{digitn:36}'

[[tables.table.column]]
name = 'firebase_id'
valueType = 'fakeit'
value = '{digitn:36}'

[[tables.table.column]]
name = 'created_at'
valueType = 'value'
value = '{now}'

[[tables.table]]
name = 'user'

[[tables.table.column]]
name = 'id'
valueType = 'fk'
value = 'account:user_id'

[[tables.table.column]]
name = 'name'
valueType = 'fakeit'
value = '{name}'

[[tables.table.column]]
name = 'icon'
valueType = 'fakeit'
value = '{url}'

[[tables.table.column]]
name = 'created_at'
valueType = 'value'
value = '{now}'
