[db]
name = 'db'
user = 'user'
password = 'password'
addr = 'localhost:3306'
net = 'tcp'
parseTime = false
location = 'Asia/Tokyo'
allowNativePasswords = true

[tables]
[[tables.table]]
name = 'user'

[[tables.table.column]]
name = '1'

[[tables.table.column]]
name = '2'
