[[tables]]
name = 'account'
want = 1

[[tables.columns]]
name = 'user_id'
valueType = 'fakeit'
value = '{digitn:36}'

[[tables.columns]]
name = 'firebase_id'
valueType = 'fakeit'
value = '{digitn:36}'

[[tables.columns]]
name = 'created_at'
valueType = 'value'
value = '{now}'
