[[tables]]
name = 'user'
depends = ['account']
want = 1

[[tables.columns]]
name = 'id'
valueType = 'fk'
value = 'account:user_id'

[[tables.columns]]
name = 'name'
valueType = 'fakeit'
value = '{name}'

[[tables.columns]]
name = 'icon'
valueType = 'fakeit'
value = '{url}'

[[tables.columns]]
name = 'created_at'
valueType = 'value'
value = '{now}'
